### ISSUE TITLE
distributing CLI tools as self-contained binaries

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#32]
@ahmadnassri brought this up at JSConf EU.  would like to invite him to a meeting to chat about it, as I think it falls within our scope.

**Comment by bengl** [comment]
Here is some prior art from forever ago: https://github.com/bmeck/noda-loader

**Comment by joyeecheung** [comment]
I believe at the moment to do something like this the user has to hack the entry point somehow (e.g. using `_third_party_main.js`  in the https://github.com/bmeck/noda-loader mentioned above) and build the binary from source. I am working on a way to customize the entry point from the embdder API (https://github.com/nodejs/node/issues/23265) so that it's at least covered by our cctests ([WIP](https://github.com/joyeecheung/node/tree/use-main-in-test)), that might be a reasonable first step to get rid of this hack (still requires compiling C++, but it only needs to link to the library instead of compiling everything from scratch).

**Comment by sam-github** [comment]
I think that there would be willingness on the part of core to make changes to accomadate the building of an app bundler, but someone would have to step up to do the work on the bundler, and make some specific requests of core (or PRs!) that would make the bundling work easier.

Besides snapshot and code cache, I think that patching in a VFS would also be a common requirement, because at the least require (and also fs.open for bundled assets?) would have to redirect to files bundled into the executable.  Or, @joyeecheung , do I misunderstand what you mean by code cache? Is it the lib/**/*.js files we compiled into node? I think its different, a V8 optimization.

Personally, I'd be :+1: to even going so far as to having standard runtime feature like `node --bundle /some/app -o app.exe` option, but that would take a really robust user-land implementation first (with features added incrementally to core to make building it easier).

This also might interact with WebPack, I think I've heard some people suggesting it as a way to build self-contained CLI apps, but I don't know enough about it to understand whether that is actually possible, or perhaps I've even misremembered.

**Comment by joyeecheung** [comment]
@sam-github By code cache I meant the binary blobs passed into the V8 API along with the source code when compiling scripts. Although for support of this I *think* it may be more transparent than the snapshot (e.g. we can just use an internal cache map in C++ land for `internalBinding('contextify').compileFunction()`. The resolution from specifier to the actual source code can be then separated from this either in build time or in run time).

**Comment by refack** [comment]
FTR we currently run several optimization on the stdlib code.
1. We transcode the .js file to `const uint16/8_t vars[]` in `tools/js2c.py` and embed that into the binary. _This part __is__ enabled for something like the `_third_party_main.js` entry point, with `./conifugre ... --link-module=gaga.js`._
2. We pass that code to V8 to parse, then serialize the V8 "code cache" and embed that into the binary, so that parsing and compilation of JS code is minimal, that's in `tools/code_cache`.
3. Optionally we serialize the complete state of V8 as a "snapshot" and embed that into the binary, that's in `tools/snapshot`.

**Comment by ahmadnassri** [comment]
happy to chat more and provide more context in next meeting :+1: thank you for opening the issue @boneskull

**Comment by ahmadnassri** [comment]
some context:

as a CLI developer, I'd like to be able to ensure my users are getting pre-compiled instances of my application, with minimal overhead _(only bundle the needed internal dependencies for my app)_ and with controlable target distribution _(i.e. pre-compiled binary, so I don't have to rely on the user's environment and compatibility)_

examples in the wild that attempt to address this: 

https://github.com/zeit/pkg
https://github.com/nexe/nexe
https://github.com/igorklopov/enclose

as per @joyeecheung all of these _(since I last inspected them)_ rely on hacking the entry point, then proceed to compiled node itself as per-usual, with targetted distributions for different environments _(win, darwin, linux, etc ...)_

I'm not an expert on binary packaging and distribution in this context, but I'll attempt to further articulate my thinking:

the main point to make here perhaps is: while these tools are "getting the job done" ... they are actually compiling and distributing node itself, while bundling some `node_modules` and hacking an entry point...

vs. 

**Idea 1** node's official binary can somehow wrap an `app`'s folder with knowledge of it's entry point _(i.e. keeping the app development process separate from the compiling and packaging process)_ 

then with an additional command, re-package a secondary binary with the app's logic included?

**idea 2** provide build tooling and configuration that app developers can customize and optimize for best use of their CLI app ... including the ability to only include relevant APIs to the CLI ... _e.g. I don't need `http` and `crypto`, turn those off, just need `fs`, and few other internals ..._

**Comment by boneskull** [comment]
here’s a new one https://blog.cribl.io/2019/07/08/going-native/

**Comment by ledbit** [comment]
As the author of the blog post that @boneskull posted above I'll list some of our requirements and what I think should **not** be done as part of native bundling work:

Native bundling should be:
1. responsible for embedding the application into the binary
2. ensure that the bundled applications behaves exactly the same as when running `node app.js` (not yet possible with [js2bin](https://www.npmjs.com/package/js2bin))
3. able to embed/bundle precompiled `.js` (snapshots or anything that can make the load time faster)
4. able to support native add-ons - would require platform specific recompilation 

Native bundling should **not** be:
1. responsible for packing the application or it's dependencies (use webpack, rollup etc to get a single `.js` file)
2. packing any data files - ship those as part of the application's package/archive

**Comment by ledbit** [comment]
@joyeecheung, @refack - a couple of questions around snapshots:
1. are there any restrictions in what `.js` can be snapshot? 
2. is it fair to assume that there are no real space savings between `.js` and a snapshot (but there are startup cost savings) 

I've looked at `tools/code_cache` and `gen/node_code_cache.cc` and is seems possible to do something similar to `js2bin` along the lines of :

1. have a static array with `magic` content with predefined size, say 1MB 
2. add it to `code_cache`
```
  code_cache.emplace("magic_main",
    std::make_unique<v8::ScriptCompiler::CachedData>(
      magic_main,
      static_cast<int>(arraysize(magic_main)), policy
    )
  );
```
3. then allow users to be able to run something like `node --embed bundledApp.js --output=MyApp`, which would:
  a. compile `bundledApp.js`
  b. read current `node` and replace the magic array with the content from (a)
  c. write that out to a different file 

When executing `MyApp` there would be logic to detect if `magic_main` was present and if so control be passed to it. 

Thoughts/ideas?

**Comment by mhdawson** [comment]
@ledbit quick question.  Are different linux variants supported (ex power or s390x?)

**Comment by ledbit** [comment]
Right now the list of supported platforms (in js2bin) is the most common plats I was able to easily get CI/CD going, but the same method should work anywhere NodeJS compiles. I'd recommend moving this convo to the [js2bin repo](https://github.com/criblio/js2bin/issues)

**Comment by boneskull** [comment]
Is addressing shortcomings in the "embeddable API" is a prerequisite to an ergonomic way to bundle self-contained binaries?

@joyeecheung I'm ignorant about the state of things on that front, so I don't understand [from your comment](https://github.com/nodejs/tooling/issues/32#issuecomment-500958552) whether exposing more/better embeddable APIs is needed to get to "code cache & snapshots", or whether "code cache & snapshots" is wholly a performance improvement, or if it would also positively impact DX?

How would "embedded Node.js", code cache & snapshots be _inline with_ or _orthogonal to_ @ledbit's strategy?  In other words, if these were available, would @ledbit change js2bin's approach to leverage them?

**Comment by boneskull** [comment]
This landed: https://bellard.org/quickjs/

Interesting but also just a JS runtime. It apparently compiles to binary executables

**Comment by joyeecheung** [comment]
> are there any restrictions in what .js can be snapshot?

There are several restrictions, in Node.js core these are enforced with assertions though in user land the restrictions may be relaxed a bit. For example:

- There should be no asynchronous tasks in flight, either in the microtask queue, nextTick queue, or the libuv queue. It's not impossible to be able to restore from a pending queue in the snapshot but it would be very tricky as there are many states you need to maintain consistency for.
- Command line arguments and environment variables should not be accessed when building Node core's environment-independent snapshot. For user land snapshots, it may not be entirely necessary, but it depends on whether the user application want to accept configuration from those and how difficult it is to maintain consistency with different set of configurations during built time and run time.

> is it fair to assume that there are no real space savings between .js and a snapshot (but there are startup cost savings)

There would only be a space overhead in exchange for startup performance. The JS engine cannot just discard the original source code because it still needs to lazily recompile things and allow user to see them for debugging purposes.

**Comment by joyeecheung** [comment]
> When executing MyApp there would be logic to detect if magic_main was present and if so control be passed to it.

You are describing how `_third_party_main.js` currently works. The user has to recompile Node.js itself with the original source code plus `_third_party_main.js` placed inside `lib/` under the source directory, as Node.js does not itself come with a C++ compiler.

**Comment by joyeecheung** [comment]
> ..exposing more/better embeddable APIs is needed to get to "code cache & snapshots", or whether "code cache & snapshots" is wholly a performance improvement, or if it would also positively impact DX?

As mentioned in https://github.com/nodejs/tooling/issues/32#issuecomment-510643515 above effectively you need a C++ compiler to generate an executable like this. What Node.js core could do is to make it less painful - say, instead of having to build Node.js core, you can just statically link to some prebuilt Node.js library with an embedder API that allows you to hook into the entry point and a virtual file system. `libnode` is currently far away from being able to enable that (we can't even test it in our cctests).

It's less of a big deal to include code cache customization in such embedder APIs but it would be trickier for snapshots for the reasons mentioned in https://github.com/nodejs/tooling/issues/32#issuecomment-510638872

**Comment by ledbit** [comment]
> You are describing how _third_party_main.js currently works. The user has to recompile Node.js itself with the original source code plus a custom _third_party_main.js placed inside lib/ under the source directory (which Node.js magically knows to pick up if it exists and use as entry point), as Node.js does not itself come with a C++ compiler to ...

Correct (almost). Now, from a user/developer point of view what I am trying to avoid requiring the C++ toolchain. The approach that I took in [js2bin](https://github.com/criblio/js2bin) is **to embed some placeholder content** into `node` at build time which will then get replaced at app build/bundle time - besides `node` size, do you see any other issues with this approach?

[in original comment](https://github.com/nodejs/tooling/issues/32#issuecomment-509450453)
> have a static array with magic content with predefined size, say 1MB

**Comment by ruyadorno** [comment]
This idea has moved to its own initiative: [Node.js SEA Team](https://github.com/nodejs/single-executable), spawned by a mixed cohort of new and long time Node.js collaborators 🎉 

Make sure to follow activity in that repo in case anyone is still interested in distributing CLI tools as self-contained binaries.

**Comment by abdennour** [comment]
Since Node 20.x.x , it has been there: https://nodejs.org/api/single-executable-applications.html
