### ISSUE TITLE
openjs summit session tracking issue

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#74]
SCHEDULE: https://openjscs2020.sched.com/event/clHF/nodejs-tooling-group-collaboration

See https://github.com/openjs-foundation/summit/issues/299

**Comment by boneskull** [comment]
@nodejs/tooling 

we need an agenda.  We can just pull stuff off of the list like usual, but we're also likely to have more participants that aren't normally involved.

the way this usually goes is that we give an introduction to what the group is and what it does and what it's done.  that's fine

personally, I like to get more ideas from the community about what's important to them and what pain points they are having.

**Comment by darcyclarke** [comment]
I'd like to propose an agenda item:
- [ ] Discuss adding a standing **mob programming** session alongside our weekly call:
  - would be a 1hr timeslot (don't need to use the entire session if there's no work to be done)
  - would happen after our weekly call (so that we can discuss work before diving in)
  - we'd have a rotating "driver" &/or can rotate during the session if it makes sense
  - this should help push work forward (as it forces some dedicated time to be allotted to resolving our backlog) & garner better consensus/understanding

**Comment by bcoe** [comment]
I thought it worked well at the last event where we floated a few topics we were thinking of covering, and allowed the attendees to pick a few for discussion. Given our hour slot, perhaps we could cover 2 or 3 ideas.

**Comment by iansu** [comment]
What time is this meeting? The schedule doesn't include a timezone. Is it June 25th at 12pm Pacific?

**Comment by bengl** [comment]
@iansu The time zone for the schedule is UTC-5 (i.e. CDT), so the meeting is scheduled for 2pm EDT, 11am PDT. (I hope I did that math right?)

**Comment by bcoe** [comment]
I was given a calendar invite, as I'm co-hosting the session, it's 11AM PDT (Ben time).

**Comment by bengl** [comment]
> I thought it worked well at the last event where we floated a few topics we were thinking of covering, and allowed the attendees to pick a few for discussion. Given our hour slot, perhaps we could cover 2 or 3 ideas.

I'm all for this. I'd recommend avoiding fs hooks as a topic though, since that's being covered in the sightly-overlapping Unified Hooks meeting.

**Comment by boneskull** [comment]
agree w/ @bengl

**Comment by boneskull** [comment]
can somebody volunteer to take notes

**Comment by boneskull** [comment]
I guess that somebody was me.

Minutes landed in f9bb0d9b3c0853fd2ce1a0cf1cad40ddd6d34456
