### ISSUE TITLE
the creeping scourge of tooling config files in project root directories

### ISSUE THREAD

**Issue by boneskull** [nodejs/tooling#79]
Splitting this out from #71 which was rather broad.  There are (at least) two separate issues there; one is where user-specific config files should live, and another is where _project_-specific config files should live.  This issue is about _project_-specific config files. 

The files we're talking about are configuration files for _development dependencies_ and are committed to VCS.  

Many projects suffer from the problem of _too many config files in the project root_, as @iansu [tweeted](https://twitter.com/iansu/status/1126512410313891841?s=20):

![image](https://user-images.githubusercontent.com/924465/87209560-2b5cbd80-c2c7-11ea-8762-2d65515c1aab.png)

We put config files in the project root _because we put config files in the project root_.  There is no reason other than a _lack of an alternative convention._

We can do better than this. The idea is we aim for a "critical mass" of popular tooling authors moving their project-specific configuration to a subdirectory (e.g., `.config/`).  If we can agree on a subdirectory, and change our tools to support the new subdirectory, we will significantly reduce this problem.  It's our hope (though not a strict requirement) that the convention we agree upon will be flexible enough to reach beyond the JS ecosystem.  For instance, your `.travis.yml` and `netlify.toml` could live in this directory as well, if this idea becomes popular enough.

We should get buy-in from maintainers of popular tools; if these tools adopt the new subdirectory, it's likely the ecosystem will slowly follow suit.

cc @nodejs/tooling @nodejs/package-maintenance

**Comment by styfle** [comment]
Would this new subdirectory also include `package.json` config?

**Comment by boneskull** [comment]
@styfle Whether any given tool uses the subdirectory is up to the maintainers of that tool.  For npm in particular, this seems like perhaps a risky move, given there are many assumptions across userland tools about where `package.json` lives.

**Comment by boneskull** [comment]
(It's not really npm's to move, either...  they aren't the only consumers of it, obv)

**Comment by coreyfarrell** [comment]
Moving `package.json` to a subdirectory would also be problematic for Node.js where the [package.json "type" field](https://nodejs.org/dist/latest/docs/api/esm.html#esm_package_json_type_field) is set.

**Comment by ljharb** [comment]
Moving eslint config would be problematic for the same reason, since it composes up the hierarchy, and describes the current folder.

**Comment by bcoe** [comment]
what if a folder such as `.config/` had identical semantics to if the file existed in the root? e.g., `test/.eslintconfg.json` still took precedence.

**Comment by ljharb** [comment]
Then how would I lint my JS config files inside `.config`?

**Comment by boneskull** [comment]
I don’t think that’s an unsolvable problem.

**Comment by ljharb** [comment]
It’s a problem that doesn’t need to exist tho. I think it might make sense to come up with a conventional location for some kinds of config files - project-level ones, mainly - but not for directory-level ones, like eslint/babel/npmrc/gitattributes perhaps/etc.

**Comment by jedwards1211** [comment]
@ljharb well `.config/.eslintrc` would apply to JS files inside `.config` since it applies to the parent folder.  There would only be an issue if you JS files in `.config` and parent folder to be linted differently.

@boneskull on the other hand, IDEs could be made to show dotfiles in a pseudo-directory.

I agree that this becomes a bit disorienting, especially when I have a bunch of project folders open in my workspace and I'm scrolling between them.

**Comment by ljharb** [comment]
Yes, i would assume my config file would match the node version eslint runs in, but my actual files would match the node versions my production code targets - iow i think that’s the most common case.

**Comment by ahmadnassri** [comment]
this issue mentions "user-specific" and "project-specific" config files, I would argue, while those are important and the noise ratio is quite high per project, a more important vector is **"org-specific"** config files.

regardless of team size, small and large teams might be in a situation where they have to manage hundreds of projects (up to thousands in case of enterprises), those projects might be independent repositories or a collection of mono-repos with many packages and/components within.

a potentially more inclusive approach to consider here, is having a central external spot for all config files, that apply by default to each project / repo, and any local file is considered inheritance / override, thus the Patten becomes:

- no local configs => use org-wide defaults
- some local configs => use org-wide defaults and override specific declarations

this would massively shrink the configuration footprint, for both individuals and teams.

some good relevant references here (though still rely on a local file)

- [`eslint` shareable configs](https://eslint.org/docs/developer-guide/shareable-configs)
- [`semantic-release` shareable config](https://semantic-release.gitbook.io/semantic-release/extending/shareable-configurations-list)
- [`probot` "extends"](https://github.com/probot/probot/blob/3f0491f63b854de5372e8bed0017b87c8762297e/docs/best-practices.md)

**Comment by ljharb** [comment]
a config tho that lives outside the repo won’t be easily shareable across multiple devs.

**Comment by ahmadnassri** [comment]
> a config tho that lives outside the repo won’t be easily shareable across multiple devs.

I would argue eslint, semantic-release, renovate bot and others have done a good, positive job of setting a pattern here (they use packages) that make it easily shareable

**Comment by ljharb** [comment]
Totally! But those all use per-directory config files, even if they reference a shared config. You’d still need a way to target an individual directory with its own config, which is what eslint config flies already achieve. Moving them into another folder adds complexity because *that folder* needs its own settings too.

**Comment by ahmadnassri** [comment]
yep, agreed. I don't have a good answer / follow up to be honest. I wanted to at least have a mention of a 3rd "vector", beyond user, and project to be included in case someone has some further patterns to surface 

I've solved this problem in the past by using Docker as the build tool, a central "org-wide" image (named "build-essentials") that hosts all the actual dev dependencies (webpack, eslint, etc..) with a single Dockerfile per repo that I inherits "FROM" it, repos optionally have overriding local configs, but the defaults are all hard-coded in the build image.

I also realize "use docker image dependencies" is not necessarily the approach sought here, but worth a mention as a reference how I tackled this in the past.

**Comment by shannonmoeller** [comment]
If someone wants to add support for this pattern to their module, I created https://github.com/shannonmoeller/find-config back in 2015 for exactly this reason. Glad to see this idea being championed agin.

**Comment by boneskull** [comment]
fwiw, with eslint, I avoid putting eslintrc files in multiple directories, and instead use the `overrides` section in a single root config file to control directory-specific configuration.  I would not use multiple config files unless that root config became massive.

**Comment by wesleytodd** [comment]
I think a great next step would be to chat with @nzakas and the other ESLint maintainers, as that would be one of the most widely impactful projects to support this.  Maybe also @hzoo and the other Babel maintainers.

**Comment by jkrems** [comment]
I think a potential alternate perspective: Putting all those files config files into `./.config` seems a bit like sweeping the problem under the rug. There's still 10s of config files with potentially overlapping settings that may need to be updated and/or referenced while trouble-shooting. They are just a bit harder to find now. To me a more interesting problem would be - could the number of those files be reduced somehow?

**Comment by wesleytodd** [comment]
> hey are just a bit harder to find now. 

If you take a look at many projects, these files are rarely changed.  It is very common for you to see 10 files at the root of a project which haven't been changed in 4 years, when the `lib` or `src` directory was changed last week.  IMO, this is a great reason to make them harder to find.

> could the number of those files be reduced somehow?

It can, use less tools.  I kid a bit, but seriously the number of config files is IMO a "smell".  There are some reasons which are valid and bring enough value to a project to make it worth it, but shifting complexity from a number of files into less files most likely will not remove the complexity.  The only way is to *actually remove the complexity* by removing the tools or some feature of those tools.

> I would argue eslint, semantic-release, renovate bot and others have done a good, positive job of setting a pattern here (they use packages) that make it easily shareable

This is one great point, if you can make great defaults or easily shareable configs, this problem is reduced.  This is basically the only reason I use `standard`, it bundles up the config file into a package install, moving the complexity from my source code into it's source code.

**Comment by jedwards1211** [comment]
@jkrems 
> could the number of those files be reduced somehow?

Personally I like putting config in package.json for tools that support it.  Some people don't like the extra bytes winding up in the package though so it would be nice if npm had a built in way to exclude some keys in package.json from publishing.

Or maybe if you use something like https://github.com/romefrontend/rome, but it's hard to imagine Rome will be able to beat all these other specialty tools at their own game.

**Comment by jedwards1211** [comment]
I get the impression half the reason Sindre Sorhus made XO is just so that he could have the linter defaults he wants without any extra configuration.

**Comment by bnb** [comment]
> Personally I like putting config in package.json for tools that support it.

Quite honestly, a solution I'd prefer to see: instead of trying to force a best practice on the ecosystem, support defining this in package.json. Have a `configs` property (using the name previously shared) that either has a string value of a path that configs can be found in or is an object whose properties are the name of the config (i.e. `babel`) and the value is the relative path to the config. Tooling could read read that and let people shove them wherever they want - in a .configs directory or anywhere else.

**Comment by ljharb** [comment]
Another direction to pursue, as opposed to trying to change "there's config files in the root" (since there are often good reasons for it), would be asking github if there's a way to hide those dotted config files on first view of the repo page (with a "show config files" button, or something).

**Comment by shannonmoeller** [comment]
Toggling visibility of dotfiles on github is a bad idea as it would be a convenient place to hide malicious code. It also doesn't catch files like `*.config.js` or `config.*.js`.

**Comment by Eomm** [comment]
> Toggling visibility of dotfiles on github is a bad idea as it would be a convenient place to hide malicious code. It also doesn't catch files like `*.config.js` or `config.*.js`.

I agree.

If the target is to ease the project navigation I'm not sure that suggesting a new plugin/tool to be installed in the IDE would be the solution.

I would use the [`directories`](https://docs.npmjs.com/files/package.json#directories) object that npm is already supporting.
We could add a `conf` key that defines the root path to the config files.

Tools should read that path (if any) to get the config.

Regarding 

> You’d still need a way to target an individual directory with its own config, which is what eslint config flies already achieve

I think that all remain as is: the user will add that file in the right dir
this setup will change only the load of the "root" config, without changing the cwd.

> those projects might be independent repositories or a collection of mono-repos with many packages and/components within.

For this approach, instead, I can think only to a new `lerna` command.. not sure how to deal with this use case since there could be many conflicts if those components use different major versions (thanks to legacy code of course 😀)

**Comment by nzakas** [comment]
At least once a year someone asks ESLint to move our config files into a new directory to avoid "too many config files in the project root." Each year we say the same thing: as long as you don't pepper your project with `.eslintrc` files, you can move your config file wherever you want and use the `-c` command line option to read it. 

FWIW, we're working on a new config system (https://github.com/eslint/rfcs/tree/master/designs/2019-config-simplification) that will eliminate the hierarchical/cascading config part of the system, but our advice will still be to use the `-c` flag to specify which config file you want load.

I really think the long-term solution is just for tools to allow end-users to specify where they want their config files to be loaded from and not try to get everyone to agree to store config files in a specific directory.

**Comment by qballer** [comment]
@nzakas made some valid points with the -c option. To add on top of that I believe config files should be explicit and not implicit. Meaning the default option should be to mention the required config. This can give package authors the time to think where they want to put their config files. This could be annoying in the terminal but solvable via the scripts.  

Another somewhat hacky idea is to monkey patch the fs for common config file. I'm unsure what are the proper ascetics of this.

**Comment by shannonmoeller** [comment]
> use the -c command line option

Thank you for supporting this command line flag. It's a great start. But many users make use of GUIs, IDEs, or daemons which don't support setting command-line flags. And the onus is still on users to create bespoke solutions per project. It's disheartening to see when there's a well-documented open standard like XDG that would fix the problem for thousands of developers if a few dozen tools would agree to support it:

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by dominykas** [comment]
I strongly disagree with the idea that tools should always explicitly take a config option from the CLI and not provide a default. That would result in very poor UX and a lot of extra work for developers using such tooling. I'd like to focus on productive work and making fewer decisions, not more, please.

> GUIs, IDEs, or daemons which don't support setting command-line flags

Or even environment variables. Which is what XDG relies on? However it has to also be said that XDG is more geared towards global configs? And it's also Linux only?

> I would use the directories object that npm is already supporting.

I'm very much not against this idea, but I suspect that having a smart default would probably gain more adoption?

**Comment by varunarora** [comment]
I don't intentionally want to play devil's advocate here, but just want to understand what the issue is here. 

The fact that the root directory has a lot of config files? And that the directory on a user's computer looks very filled up when they clone or fork it?

I consider myself a deeply design-savvy programmer, but am unable to see the problem here. There are tens of solutions, of course, but please could you help me understand what you consider to be the pain here?

**Comment by dds** [comment]
> We put config files in the project root because we put config files in the project root. There is no reason other than a lack of an alternative convention.

Is the problem with putting them in the root directory of the repo that GitHub's UI is devoting a lot of screen real estate to dotfiles that would be hidden if we cloned the repo locally? Could we petition GitHub to not show files beginning with a `.` by default, perhaps showing them hidden with a rollover?

**Comment by jspears** [comment]
I wrote [mrbuilder](https://mr-builder.github.io) to help solve this issue.  Particularly in monorepos.   Its kinda like a universal configurator for webpack,eslint,karma and a ton of others.

**Comment by sneak** [comment]
The root is a good place for project-wide settings. 

GitHub should hide dotfiles by default, like ls does. They are dotfiles for a good reason.  Perhaps other metadata (like package.json) should also be dotfiles.

**Comment by DanielTate** [comment]
> Would this new subdirectory also include `package.json` config?

This might cause issues for npm script execution?

**Comment by intrnl** [comment]
> Would this new subdirectory also include `package.json` config?

Moving `package.json` to `.config` folder seem like an odd choice, given that some of its fields are more of a metadata in a sense. 

First off, who is the intended target for this new `.config` folder? Is it only for tooling/development, or is it also a place to put files necessary for runtime?

I suppose given the title this would've meant for tooling/development, so here's what I propose. Keep the necessary fields like `name` `dependencies` and post/preinstall `scripts` on the project root folder, but for the rest like `publishConfig` or build `scripts`, move it into `package-dev.json`

**Comment by alganet** [comment]
The IETF folks solved this problem on URIs using a `.well-known` namespace:

RFC about it: https://tools.ietf.org/html/rfc5785
Also: https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers

**Comment by intrnl** [comment]
> The root is a good place for project-wide settings.
> 
> GitHub should hide dotfiles by default, like ls does. They are dotfiles for a good reason. Perhaps other metadata (like package.json) should also be dotfiles.

Hiding config files because they are dotfiles is an odd choice, I think most devs would just turn it off because it hinders their ability to poke through the project from the website, and most beginners would find it confusing because it looks as if their config files didn't make it onto the git repository (not everyone knows Unix conventions).

**Comment by lyjia** [comment]
Perhaps the problem is too much tooling. Config files in the project root is an old and time-honored convention, and this issue seems to be more about aesthetic preference than good practice.

**Comment by wyaeld** [comment]
I don't like the idea of hiding them.
What would be good is having a common standard for "configlocations" file, (call it whatever people agree) that just has entries for locating various config files.
Then if I want to put all my editorconfig and eslint things under /config, I can.
By default nothing changes, but as tools, eg. NPM, offer support for this configlocations file, then I just organise.
Opt-in won't break anything, but there is no implicit or assumed behaviour. 
Then need a critical mass of tooling to add support it.

**Comment by shannonmoeller** [comment]
As stated previously, hiding files in the github UI is a security issue and is inadvisable.

Saying that you don't see an issue doesn't negate that many others do.

**Comment by hussaibi** [comment]
_Disclaimer: I came here from HN. I've never looked at this repo. I have no business telling people close to the problem what to do. But, I think tunnel-vision is happening._

My understanding of the problem: mandatory hardcoding of configuration files are causing a code smell. 

I agree. The code smell is that this is bad aspect oriented programming. Packages should be reserving config prefixes and allow user-defined prefixes to be applied on code arbitrarily. Thus, application aspects should have their own config prefix, all in one file.

The Java Spring Framework does this ^ via Java [annotations and application properties/yaml files](https://www.baeldung.com/configuration-properties-in-spring-boot). Python is now able to do this via Facebook's [Hydra library](https://hydra.cc/docs/intro#basic-example) (monkey-patching as was earlier mentioned).  Unfortunately, it requires 2 things:

1.[JS Decorators](https://github.com/tc39/proposal-decorators) (mandatory)
2. [JS Class Fields](https://github.com/tc39/proposal-class-fields) (for better UX)

But all this ^ only address application properties for different environments (i.e. default, local, dev, test, qa, prod). So this would effectively reduce the `.js` config files down to the # of application environments you're deploying to.

I don't know what the project's ES version being used, but I'll guess it's not using proposal language features. This ^ likely isn't something that can be effectively adopted at this time. 

---

If possible, I'd defer taking action until JS Decorators and Fields can be used to refactor the tooling w.r.t its config dependencies.

**Comment by kuon** [comment]
For compatibility I have some wild idea.

Maybe we could  (I mean for projects in general as this issue is going a bit out of scope, came from HN) start using `.config` (or similar) immediately, and have a tool stow those files to the project root (similar to GNU Stow).

The immediate workflow would be something like:

- create `.config/`
- move all project config in it
- add `.config/` to VCS
- symlink everything in `.config/` back to project root `..`
- add all those symlinks to `.gitignore`

Ideally git could have a `stow` feature that does this automatically.

This is just an idea, I have looked in it in details, but I use gnu stow to manage my dotfiles.

**Comment by immanuelfodor** [comment]
Maybe it's time to standardize default project folders as Linux has `/etc`, `/usr`, `/lib`, `/var`, and so on? 

It wouldn't need to say where to put JS files or Java source code or PHP files, just the high level architecture of a standard development project. For example, a raw braindump just to get the hang of it: 

- `/docker` 
- `/config`
- `/k8s`
- `/src`
- `/vendor`
- `/build`
- ... 

Maybe these could have their `/.../local` version in the standard, I don't know. But we could figure it out together and make it standardized.

**Comment by sergeykish** [comment]
@kuon it is much simpler if you symlink another way

* create `.config/`

* symlink files in project root to `.config`, `.gitignore` them

* hide project root files (nautilus hides `.hidden` though extended attributes would be better, simpler to patch `ls`)

This way everyone may configure as way wish - `config` or `.config` or `docker`, `k8s` by  @immanuelfodor, no need to change tools, no suffering by those who likes status quo. And some day there would be no need to decide should the file be hidden upfront (with dot).

**Comment by extrowerk** [comment]
While i support moving the config files into a subfolder, i am vehemently against using dot-files and dot-folders. This is *nixism, and we all know well how big mess this strategy made in our $HOME, so consider use a simply named folder for this, and don't try to cover your back with bs like "Well, *nixes doesn't lists those folders, so if we can1t see there is no problem!" because there are operating systems other than *nixes too on planet earth .

**Comment by sneak** [comment]
Collapsing hidden files in the GitHub UI is not a security issue at all, any more than code or configs in a folder is; in both cases it's a click away.

**Comment by kajmagnus** [comment]
Is it necessary to hide the config folder and files — I mean, `.config` instead of `config` or `conf`?

(most people here write  `.config`)

Or would it be nice to see config files by default e.g. if opening in a file system browser
— meaning, `conf/` or `config/` (no dot).

(However, `.well-known` with dot  `.` makes totally sense — that directory isn't so interesting in itself, for humans; it just tells the not-so-bright computers where to find things.
I like the `.well-known/` approach :- )  )

**Comment by timotgl** [comment]
What if the tools adopted using environment variables to customize the location of the root config file? Something like
```
ESLINT_ROOT_CONFIG_PATH=./config/.eslintrc
```
And the config file would be interpreted as if it was actually located in the root.

So you'd need for example only one `.env` to get all the rest of the files out of the way. Or just the ones bothering you.

**Comment by t0suj4** [comment]
I think this could be solved via overlayfs and editor plugin.

All you need is a FS driver and time to develop the plug-in that would mount the config directory and hide the files again.

It's IMO much simpler than demanding cooperation across projects if all you want is to get configs off your sight.

**Comment by DylanVann** [comment]
If popular tools would standardize on something like [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) support for a config folder could be done there, in one place.

Personally I like to put configuration in package.json.

**Comment by mslinn** [comment]
A documented series of fallback directories is a standard that *nix has used for decades. X11 has probably taken this concept too far. 

At a minimum, tooling could look for config files in the following order. In this example I use the token `{root}` to mean "the top-level directory of this project's directory tree":
```
config/
{root}
```

Get fancy with per-user config to augment per-project config.
```
config-user/
config/
{root}
```

Per-user config would not be checked into git due to the following entry in `.gitignore`:
```
config-user/
```

**Comment by fregante** [comment]
Please don't make configuration tools more complex. It can't get any easier than this: 

- configuration files are at the root; everything below is affected by them

It has always worked like this, with very few exceptions using `~/.config/*` instead of just `~/.*/`; they're the **exception**.

There's already a convention for this issue: **config at the root, and app files in sub-directory/ies.**

---

If you're annoyed by config files on GitHub, have a look at https://github.com/sindresorhus/hide-files-on-github

**Comment by coreyfarrell** [comment]
> > Would this new subdirectory also include `package.json` config?
> 
> Moving `package.json` to `.config` folder seem like an odd choice, given that some of its fields are more of a metadata in a sense.
> 
> First off, who is the intended target for this new `.config` folder? Is it only for tooling/development, or is it also a place to put files necessary for runtime?
> 
> I suppose given the title this would've meant for tooling/development, so here's what I propose. Keep the necessary fields like `name` `dependencies` and post/preinstall `scripts` on the project root folder, but for the rest like `publishConfig` or build `scripts`, move it into `package-dev.json`

Having a package-dev.json might be worth considering.  In this scheme tools which will load config from package.json could look for package-dev.json as well, prefer to grab config from package-dev.json if found.  A project could configure supported tools in that single file without bloating the published size of the package as happens when putting a large number of development settings in package.json.

A project moving fields used by npm into the package-dev.json would require caution as doing so would force projects to require contributors to use some future version of npm to develop (but not matter to end-users).  CC @ruyadorno any thoughts from the npm side about this?

**Comment by ntotten** [comment]
This feels more like personal preference and something that could be done in editors rather than globally. For example, it would be fairly easy to write a VS Code extension that organizes configs for you. You could use the settings to exclude the config files from the main explorer:

```
"files.exclude": {
    ".prettierrc": true,
    ".eslintrc": true
}
```

And then write an extension that provides a custom [tree view](https://code.visualstudio.com/api/extension-guides/tree-view) that organizes the config files in whatever way you want - could be grouped by type, etc.

**Comment by samheuck** [comment]
What problem is being solved? Why is this such an issue? Can anyone break this down beyond "It smells" or "It makes my project root look cluttered"?

As a general rule of thumb, I'm always skeptical of hiding things that are already there just to reduce visual noise. I think that if a code repository accumulates "too many" .config files, that's a thing you would want to be very visible. Especially for a programmer who may be unfamiliar with that code base. It gives you a quick way to scan for what tools may be used by other contributors. That said, sometimes rules of thumb need to be broken, but I think understanding why is extremely important first. I think Chesterton's Fence applies here: 

https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence
https://josephwoodward.co.uk/2020/04/software-the-chestertons-fence-principle

**Comment by agustif** [comment]
> This would be very weird to support in tools like ESLint, Prettier, etc. that have always assumed folder hierarchy inheritance. (_I am the maintainer of the [VS Code Prettier Plugin](https://github.com/prettier/prettier-vscode)_).
> 
> Additionally, this feels more like personal preference and something that could be done in editors rather than globally. For example, it would be fairly easy to write a VS Code extension that organizes configs for you. You could use the settings to exclude the config files from the main explorer:
> 
> ```
> "files.exclude": {
>     ".prettierrc": true,
>     ".eslintrc": true
> }
> ```
> 
> And then write an extension that provides a custom [tree view](https://code.visualstudio.com/api/extension-guides/tree-view) that organizes the config files in whatever way you want - could be grouped by type, etc.

I use this to exclude node_modules and .vscode/ settings folder from the view.

**Comment by mleonhard** [comment]
The issue fails to show that a problem exists.  It essentially just says "X is bad."  I believe that changes should be made only for reasons.  Please give reasons.

**Comment by mleonhard** [comment]
There are strong advantages to having config files in the project's root directory:

1. They show that this is the project root directory.  This is useful for programmers and tools.
1. They show that the project uses particular tools.  This is useful for new project members and old project members who haven't touched that stuff for a while.
1. In programming and system design, putting related things close together makes maintenance easier.  Config files usually apply to multiple sub-directory-trees.  The project root directory is therefore the closest position to the places where the config files are used (the sub-directory-trees).  Putting config files there will reduce maintenance effort. Maintenance is 80% of the effort put into software projects.  Reducing maintenance effort improves productivity and morale for engineers working on the project.
1. They support overrides in an intuitive way.  For example, `/proj-root/.gitignore` contains rules that apply to all sub-directory-trees and `/proj-root/abc/.gitignore` contains rules that are specific to the `/proj-root/abc/` sub-directory-tree.  This obvious-ness is lost if the files are in `/proj-root/config/.gitignore` and `/proj-root/abc/config/.gitignore`.  This also adds extra directories.  If you make the `config/` directory optional, you have introduced multiple allowed locations for config files.  Having multiple ways of doing things makes maintenance much much harder.

In absence of compelling reasons to make the suggested change, it would be good to close this issue.

**Comment by darcyclarke** [comment]
There's been some great ideas, insights & criticisms surfaced already... so, why not throw my 2 cents in for good measure. 

**First** & foremost, I think its honorable for us to try to tackle this issue holistically (*virtual pat on back to our community).

**Second**, I think it would be helpful to redefine/clarify the questions we're looking to answer & problem we'd like to solve for from the original post (especially to `root` out any assumptions - pun intended 😉):

**Questions:**
1. **Where does _project-specific config_ live today?**
2. **Is the current location of _project-specific config_ a problem?** If so...
3. **Would standardizing _project-specific config_'s location help?** If so...
4. **Where should _project-specific configs_ live tomorrow?**

**Thoughts:**
1. Anecdotally, we agree that the root of a project has become the primary - not sole - dumping ground for config today (with a mixture of options, overrides & extensions supported by the array of environments/tools)
2. I think this is the most contentious part. From a maintainers perspective (specifically `npm`): I don't think it's much of a problem today for us or many of our users/use-cases; Hypocritically, from the perspective of a user of multiple tools in my own projects: I'd appreciate a more substantial level of standardization/organization (thus, let's explore `#3`)
3. I'm concerned we're going to get into a situation where this only gets partial adoption & we now have a net-new competing standard/implementation (https://xkcd.com/927/); This would probably mean users fallback to whatever is easiest & most widely supported (ie. what is happening today). Let's assume for a minute that we could get widespread adoption of a standard, then...
4. `.config/` for _project-specific configs_ makes sense to me based on [`XDG`](https://wiki.archlinux.org/index.php/XDG_Base_Directory) (as has been proposed here by @boneskull  / @shannonmoeller) but it doesn't resolve any concerns/reservations I have for `#3`

I'm open to discussing this further, including outlining any next steps, **IF** we can get some more interest/input by more tooling maintainers. Otherwise, I think we might want to spend more time/energy on other issues.

**Comment by MrStonedOne** [comment]
> What problem is being solved? Why is this such an issue? Can anyone break this down beyond "It smells" or "It makes my project root look cluttered"?

It doesn't scale.

There is a reason github started supporting the `.github` directory.

Its as plain and simple as that.

Here is the not-stupid suggestion. `.project-dev-config/` this way it doesn't require a directory conflict with the projects actual config files, and applies universally across programming languages and frameworks.

eslint and vslint and friends are not going to have any actual trouble moving their current paradigm to using this. if you can check for a file in all parents, you can check for a file in a subfolder of all parents just as easily. and if you want to lint your `.project-dev-config` folder, you simply put that config inside `.project-dev-config/.project-dev-config`.

This is a system that will scale, every potential issue raised stems from a lack of vision, given how easily they can be solved.

>This would be very weird to support in tools like ESLint, Prettier, etc. that have always assumed folder hierarchy inheritance. (I am the maintainer of the VS Code Prettier Plugin).

If you are intelligent enough to make a linter, you are intelligent enough to abstract away the folder a config is actually in, and the folder a config applies to. I really don't know why everybody is trying to bring up excuses.

**Comment by patrickcurl** [comment]
My preference would be something like: 
 
```
.config/
-- 
- package.json
```

```
// package.json 

"default_config_path": ".config",
"config_overrides": [
	{"eslint": ".eslintrc.js"},
	{"babel": "submodule/babel.config.js"}
]
```

This allows some nice defaults.... if you leave default_config_path off, if the config doesn't exist in the root, it'll check .config, otherwise it'll ignore anything not in .config, unless overridden.

**Comment by iansu** [comment]
I don't think we're going to be able to get consensus on a new config directory. Getting all tools to allow you to customize the location of the config file seems more realistic. We'll direct our efforts at specific tools that don't allow this today.

**Comment by Z3TA** [comment]
I don't see the problem...

File-list too long to fit on screen ?

It smells like "bike shedding" - so what are the real issues that need to be solved?

**Comment by MarkKahn** [comment]
What we do, since our entire team uses vscode:

- symlink all the config files to `config/<filename>`
- hide all config files in "files.exclude" in vscode

**Comment by ssbarnea** [comment]
If you already got enough of clutter in project directory and you are the maintainer of any tool with config, check https://dot-config.github.io/ and see yourself as welcomed to join the movement. Start would be hard and I suspect that early adopters will be less mainstream tools, but once we pass a dozen I suspect it will likely explode as I doubt that the number of those loving 100 files in project root is big.

**Comment by wmstack** [comment]
I'd rather they would be called `cfg` than `.config`, as I am a fan of concise descriptions. It would also have a 3 letter name, like `src`.

**Comment by ssbarnea** [comment]
@wmstack I think you are missing the point about `.config`. Is not about the lengh of the folder, is about building on top on an already established and documented standard (XDG config) which is followed by thousands. I would personally try to avoid a "NIH" approach, even if it saves few characters. While node is very popular, it should not consider itself as a trend setter.

Sadly the cool feature that vscode introduced to collapse set of files like a folder will make is less likely to agree on getting the root cleaned. Unfortunately they decided to call this feature **file nesting** instead of using the far more popular terms like **folding**, **collapsing** or **grouping**, making it very hard to find and configure.

**Comment by wmstack** [comment]
Look, if we want to push for something, let's push for it the right way. I contend that hardcoding a `.config` file for tools to locate their configuration is better than hardcoding the files to the root. Still, it is just another thing that the developers have no choice over. I don't think we will reach an agreement on the name of the configuration file. Its name would not look right depending on the project.

Its naming style would be different from the majority of other directories, save perhaps `.github`. for a great many projects, for which, if they have other directories like `docs`, `src`, `web`, `wasm`, `deps`, `net`, for example, which have concise naming styles, would make the names inelegant.

Why hardcode that name in particular? It would be unfortunate to push for a standard without enough (collective) vision. The push should be focused on making tool makers have a CLI flag for where to locate the configuration files, instead of hardcoding a new directory. What should the fallback one be? I can't agree that `.config` is ideal, but I accept that the most important aspect is that the CLI should specify a flag for an alternative path for locating the configuration file.

The `XDG` standard has never been standardised for project root directories, which leads to this GitHub issue. I think such an *extension* of the XDG spec is not appropriate here. Tooling for a project is different from user-local configuration files, which the XDG spec targets. No reason to extend the `XDG` spec. I personally would love to put my tooling in a config directory if I had the CLI flags. Especially if I don't interact with the tooling directly from the command line, which would make specifying flags tedious.

**Comment by faigdavid** [comment]
The only possible way to reduce config clutter is to create a config-manager tool that parses well-organized config folders/files and compiles them to the correct location (project root) when needed.. Potentially, it could reduce the number of root config files from like 16 to 3 or 4. 

But we also need to consider: Would it really be neater? 

Splitting up your configurations between root .config could potentially just make it harder for people reading your project to figure out what's going on. Maybe if the config-manager's config is extremely well thought out it could be better than the current situation... Or maybe if it auto generates some "project configuration description". 

The only problem is that the way things are now seems to work pretty well. Sure it looks bad, but it just works. That said, it might be one of those "once you feel it you never go back" situations where someone makes a config-manager and suddenly everyone in the industry NEEDS it.

**Comment by fider** [comment]
Brief solution for IntelliJ IDE users is [foldable projectView plugin](https://plugins.jetbrains.com/plugin/17288-foldable-projectview).
After configured can be turned on/off using shortcut.
